version: "3.7"

services:
  gilasofttest:
    build: .
    restart: unless-stopped
    env_file: .env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=$LOG_LEVEL
    stdin_open: true
    tty: true
